version: '3'

services:
    reverseproxy:
        build:
            context: ./reverse-proxy
        container_name: porfolio-reverse-proxy
        ports:
            - 80:80
        restart: always

networks: 
    default:
        external:
            name: "nat"
        